const mongoose = require("mongoose");

const segmentSchema = new mongoose.Schema({
  name: { type: String, required: true }, // Prompt from user
  query: { type: Object, required: true }, // MongoDB query generated by AI
  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("Segment", segmentSchema);
